[google_credentials]
type = "service_account"
project_id = "customer-support-chatbot-nmaw"
private_key_id = "b43cdfc069a1ce2b1740d554815d49e6c77c8566"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwACstyYRLmCO9
Igoj4ojp6R6U85EAUjeLXIdVOgKCO5dFEFdSTgiPCGD+ztWrC4kDY7np93qFm/8s
7CRXHSktdQDEmwph2DuasWWbc4YDtUfBd5ZQXcadQ2+Ql/PC9VK5h4Gtl/kOWWEN
+CvzXYrHZtVUPidritfAnW3c79sX43di0AWfEqbGFj0R5PDNa6oI+h5ofCeQi9M0
gwenhDzyKxWj2L9QEUQJD20ICCkppDNBq92idiE+wIOegz4naqeCu4x2xHh9LWm4
ckgLzIm8OZFggoXPgqzQdidqpLACUf2+zasLJrqfOSTpDkMyuUxrwnIu2Jm5178c
NIMFQTj5AgMBAAECggEAGGlNk+I5iUqm2lrYUTXgi6Eb7skBuautrJS+6KFNK8cc
KiYkFnRgV4Zv/aeulzTYYjH43WzH/7QtZouyVqrixT1PR/XBMOUPD1u/nhod4nHI
bBssLCV1oOZzmPiahNYGDVmwMOW9U7It9gQQBIda8mFfAXpFeXMejcbIMDbMirl0
koHcvX/79CpqdbgvJ/Gtp11Rqnk0mahDe22XLJcVGyjwiYbACgl9meAne9cy81vP
V7D5N5lQ89PZa+H4YgWWqVX7Fpb/SIaboG2FBkZ+BH+kTc53IxZUdloVirpMtYmy
vrZKXzm27dpK7cKpEkFhK10T2nRuJFGqsEwA0hxmoQKBgQD2TxAXZDY+8myqIJkJ
PSXfQF1GlcA39mP8h6/9H5YhR1Yg14BT2o5zKzPfatlKoN4JEg38Q1o4NlLU/kdF
RIeTuolY32Hr7BWBRKoy58kBXGPQYFFp5819NOnItBtFpNOGuAs9CfSdYNARBHAV
NBdspgRNcvG8DaXkHeClb51FXQKBgQC27O3bb2RyhkK0rYTEzpoCoRnbYKZyFZja
HqDWiY5rXHtLW4uTXym4C30AH8hybf98CoupXiLvemiwt67QDOggmSVnVqoWEjHe
rcPCzGJ9Tn8L0RT51zgn3y4Vd4NKtvvk5/n+GWnQ4OAgykThT0cmU9hpzWk+MZRI
xe0YnE8MTQKBgQCGFtitw1J8xkE+BO0LSIy7kzC0YoX4cVxReBTo+i8jAtDypB8q
h0sRi617rZGJvTXjPj763Dfbbkd9yMhH/1zHob9v8HxAkY/LhfQaLnERGpkEMctg
ml8WEJ5NMy+9pFO7faowmqDepHvhJ8dU47z02xRwjWjodY2gOFu59J9ryQKBgFj0
ct7pFpHS1JGEaDJEvgRVT3utToPgGMrJZjGuBwISoSqORBvQhTso6wqqahGriDhL
8IrWamrGvi5hxLML874We2f7bw74niPJoI8UUTjaeVHHxUmR7Y8GKyTpT4F/5pL0
dE+rEBgxowyPEFv474Kl93HMIEfMWG3jQl9bc91pAoGBAIsh+YD+4GXVUBZyOg77
dNDvUlLDpiR6Ag+aNneU2Jts8h1ppmLiHvjtpn0hqfXqdm+nE9eqUU3/RhTY42ZQ
LQMD8TaGc01Haa4L5zmOUe4y1+RDoOjoHmtG/Us452jGIYKHAHdfaGzZcOmh1kR0
HOUM6BvvzHIrjhct6oXyR57M
-----END PRIVATE KEY-----"""
client_email = "chatbot-client@customer-support-chatbot-nmaw.iam.gserviceaccount.com"
client_id = "110160585251473078670"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/chatbot-client%40customer-support-chatbot-nmaw.iam.gserviceaccount.com"
