[dialogflow]
type = "service_account"
project_id = "customer-support-chatbot-nmaw"
private_key_id = "adf3e56c493717af7b6ad74bc9fdd04a7fdd71a8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCrlpmiiXZDyCTo
iCFaREuFO45LsnQAXuorLQJfhmiN3Di64bbLkPORibOj1T4f9XgTG/44PTk+Wwxo
ab5iB3iAiMhRx3mhogUzS+J+8SZxwFPfzhuFngnXtbOr+mSP8xHN2KUm+6MmDAw1
HinFaHraCo7sro5Ll9GrjTgULmM/hNk2kAtd6885e17aV3KrszCwnawNKCUVzAIs
3PwN/Lj77i5hDPx1zwaZcaGaKGokPqPF7Nqrp6O9nUT7PD0eSS6qGn0q5/plIQ5z
lD1gb9NXQnsZGjAE4gZeef0oSp1kQdBe2io6ed2xXyYEM3HMbd9WtaNBNfLUPB4E
7vBTV/NLAgMBAAECgf8lk9W3x0x6dTUQUF/tDH4iMDaeLWG36nW333dgt4mPh70C
u50tPH3oHLZPpCNKr4xUfxfExHhHGTG05ocCjh+JZPfzEeHLr3V9FEJIsw31roRb
/987hl3M3lN03R3ffAU3QNIDyAGjd1/KvPvBNtEJHDZdqwUb3MzwRby0b90NiX1Q
gnzJ/3I1xzbnM7qGnhZh3AkhRMlfmWqUUhRyOvbSxjtOcj5jFyQfPrsulNAu8vzK
APopza4acxHFgehFsFANc93TrOnrMF++ZyUGfj2aA7ZcvaTuPLEZuqsYjqtuDcKj
rDVSeS3iuxB/AKXTiVfT5XGBmB7yi2OuYmtw2YkCgYEA1BzXkJTQhWxn9v4vabth
s0XrBnWLYTkFzHKM2c8gEASBcPx3SlUUi0192YGca3KnANlnOacZh2X4q1t9vs+O
7N/iXIzLQGu+KMuaTjc4Q1RwKX0+mftDCyb71a0YKn9dmNpO3T4GYbcgU+QRk7yC
JFwVjuPv4fsLKJEvavFViy0CgYEAzxdEep96LzC4oHuzIRDB1QebB3Po0mTaJ9Pd
/ILRyZDg3A2CQRTXmx4hIClN/HvUaALU/SdjpboXkW6KUF65gjr2TPoIM5bq//+l
Sd0++RTNcMJ0/Z91Vw4akRalMXNVE1/8oQRJaFcntdpYgxfCBX/Efhy4sdmLVPqk
Yl9Io1cCgYAjdMrH3UhZ9TwPun+ccfkr6XUW+FEbKFgCy+clhYz7gHVOuLUMFNrB
SmvODu9huqGV78Fkjr0it/XwVvPXEIT4rZf+Fn7nPttjoF0j0/EwuA2jsc7kGG8l
jxerqSqP+AhiQ6PJMdQJQ35A56/UfT9X6pij8RApOzirSFGf08WT5QKBgA+QAxBn
/amgMq+0vBBnDvnwWWEk/8EX3SETFeKM/jD0l0FSLpCvfUhl6j1dfUPVFnA+jjz8
AcwJgQ3nzbMeezhjL/E29PjThZN5ZbV4T+wt+QZZRqtsmUfSgoKWvhFKRoFvPC/p
f468xfovj2lCls0M/fowNF0BKSxYrZPK701/AoGARdPSaYARTs/fki17Nzq4XtoD
qgOCJXVAPhoiIvz5w46UKWGXZPG7fzgYc1ockIOIpVXSAvuc2963JSjotN7Et5+s
xf9YXVP04vwqDxDPhDPqMS6Kps6c3bvEPKk4Nnf8Vm00TGdVOawZm+OXiSJe/pCk
KVnEr0w5QJAqxzkadTI=
-----END PRIVATE KEY-----"""
client_email = "customer-support-chatbot-nmaw@customer-support-chatbot-nmaw.iam.gserviceaccount.com"
client_id = "109110510350081975460"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/customer-support-chatbot-nmaw%40customer-support-chatbot-nmaw.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
